"""Core primitives for multi-loop mission orchestration."""

from .capabilities import CapabilityRegistry, default_capabilities, default_toolsets
from .models import (
    Artifact,
    Budget,
    CandidateLoop,
    CandidateState,
    Capability,
    CapabilityRef,
    Event,
    ExecutionProfile,
    FailureClass,
    FitnessScore,
    Generation,
    GenerationState,
    LedgerEntry,
    Mission,
    MissionSchedule,
    Outcome,
    PermissionRecord,
    PolicyGate,
    ScheduleState,
    SideEffectClass,
    Toolset,
)
from .failures import FailureClassifier, RuleBasedClassifier
from .hermes_runtime import HermesRunOutcome, HermesRuntimeAdapter
from .index import LedgerHit, Lesson, MissionIndex
from .leases import MissionBusy, MissionLease, acquire_mission_lease
from .orchestrator import CandidateClaim, GenerationRunResult, MissionOrchestrator, ScheduleNotConfigured
from .planning import (
    FitnessReviewer,
    HeuristicPortfolioPlanner,
    PortfolioPlan,
    candidate_capability_names,
    collect_pitfalls,
)
from .policy import PathEscape, prepare_candidate, resolve_within, side_effect_directive
from .scheduler import MissionScheduler, SchedulerTickReport, TickResult
from .onboarding import (
    CapabilityRecommendation,
    OnboardingEngine,
    OnboardingPlan,
    OnboardingQuestion,
    collect_answers,
    format_capability_brief,
)
from .runners import (
    AgentCommandRunner,
    HermesRunner,
    MockRunner,
    RunRequest,
    RunResult,
    RunnerRegistry,
    ShellRunner,
    default_runner_registry,
)
from .schedule_util import compute_next_run, parse_schedule
from .storage import MissionStore
from .verification import VerificationReport, VerificationResult, run_verification
from .agent_sessions import MainLoopSession, MainLoopSessionStore, MissionDraft, SessionEntry
from .main_agent import MainLoopService
from .agent_loop import AgentTurnResult, MainLoopAgent
from .providers import (
    OpenAICompatibleClient,
    ProviderProfile,
    ProviderReply,
    ProviderStore,
    ProviderToolCall,
)

__all__ = [
    "Artifact",
    "Budget",
    "CandidateLoop",
    "CandidateClaim",
    "CandidateState",
    "Capability",
    "CapabilityRef",
    "CapabilityRegistry",
    "Event",
    "ExecutionProfile",
    "FailureClass",
    "FailureClassifier",
    "FitnessScore",
    "FitnessReviewer",
    "Generation",
    "GenerationState",
    "GenerationRunResult",
    "HeuristicPortfolioPlanner",
    "MissionScheduler",
    "PortfolioPlan",
    "LedgerEntry",
    "LedgerHit",
    "Lesson",
    "Mission",
    "MissionBusy",
    "MissionIndex",
    "MissionLease",
    "MissionOrchestrator",
    "MissionSchedule",
    "MissionStore",
    "MissionDraft",
    "MainLoopSession",
    "MainLoopSessionStore",
    "MainLoopService",
    "MainLoopAgent",
    "AgentTurnResult",
    "SessionEntry",
    "ProviderProfile",
    "ProviderReply",
    "ProviderStore",
    "ProviderToolCall",
    "OpenAICompatibleClient",
    "PathEscape",
    "ScheduleNotConfigured",
    "ScheduleState",
    "SchedulerTickReport",
    "TickResult",
    "Toolset",
    "prepare_candidate",
    "CapabilityRecommendation",
    "OnboardingEngine",
    "OnboardingPlan",
    "OnboardingQuestion",
    "Outcome",
    "PermissionRecord",
    "PolicyGate",
    "RuleBasedClassifier",
    "AgentCommandRunner",
    "HermesRunOutcome",
    "HermesRunner",
    "HermesRuntimeAdapter",
    "MockRunner",
    "RunRequest",
    "RunResult",
    "RunnerRegistry",
    "ShellRunner",
    "SideEffectClass",
    "VerificationReport",
    "VerificationResult",
    "acquire_mission_lease",
    "candidate_capability_names",
    "collect_answers",
    "collect_pitfalls",
    "compute_next_run",
    "default_capabilities",
    "default_runner_registry",
    "default_toolsets",
    "format_capability_brief",
    "parse_schedule",
    "resolve_within",
    "run_verification",
    "side_effect_directive",
]
